import express, { Request, Response } from 'express';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { GoogleGenAI, Type } from '@google/genai';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = Number(process.env.PORT) || 3000;

// Enable CORS for all origins (allowing GitHub Pages and mobile web to call AI endpoints)
app.use((_req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With, Accept, Origin');
  if (_req.method === 'OPTIONS') {
    res.sendStatus(200);
    return;
  }
  next();
});

// High body limit to allow image uploads from high-resolution phone cameras
app.use(express.json({ limit: '35mb' }));
app.use(express.urlencoded({ limit: '35mb', extended: true }));

const APP_BUILD_TIMESTAMP = 'dp-build-' + Date.now();

// Static PWA & Asset routes with strict freshness headers
app.get('/manifest.json', (_req, res) => {
  res.setHeader('Content-Type', 'application/manifest+json');
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');
  res.sendFile(path.resolve(__dirname, 'public/manifest.json'));
});
app.get('/sw.js', (_req, res) => {
  res.setHeader('Content-Type', 'application/javascript');
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');
  res.setHeader('Service-Worker-Allowed', '/');
  res.sendFile(path.resolve(__dirname, 'public/sw.js'));
});
app.get('/icon.svg', (_req, res) => {
  res.setHeader('Content-Type', 'image/svg+xml');
  res.setHeader('Cache-Control', 'public, max-age=86400');
  res.sendFile(path.resolve(__dirname, 'public/icon.svg'));
});

// Real-time app version check for seamless live PWA updates without reinstalling
app.get('/api/app-version', (_req, res) => {
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');
  res.json({
    version: APP_BUILD_TIMESTAMP,
    timestamp: Date.now(),
    app: 'Digital Pharma',
    status: 'live-sync'
  });
});

// Helper to extract JSON from Gemini text output
function extractJsonFromText(rawText: string): any {
  if (!rawText) return null;
  const cleaned = rawText.replace(/```json/gi, '').replace(/```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    // Try finding array
    const sArr = cleaned.indexOf('[');
    const eArr = cleaned.lastIndexOf(']');
    if (sArr !== -1 && eArr > sArr) {
      try {
        const candidate = cleaned.substring(sArr, eArr + 1).replace(/,\s*([}\]])/g, '$1');
        return JSON.parse(candidate);
      } catch (err) {}
    }
    // Try finding object
    const sObj = cleaned.indexOf('{');
    const eObj = cleaned.lastIndexOf('}');
    if (sObj !== -1 && eObj > sObj) {
      try {
        const candidate = cleaned.substring(sObj, eObj + 1).replace(/,\s*([}\]])/g, '$1');
        return JSON.parse(candidate);
      } catch (err) {}
    }
  }
  return null;
}

// Regex to catch actual refusal sentences generated by vision models without blocking real medicines
function isModelRefusal(str: string): boolean {
  if (!str || typeof str !== 'string') return false;
  const s = str.trim().toLowerCase();
  // Don't flag actual medicines like "Claritek", "Clear Eyes", etc.
  if (s.length < 20) return false;
  return /tasveer.*(roshni|dubara|saf|wazeh|dhundli|dobara)|tasvir.*(roshni|dubara)|cannot read|unable to read|unreadable image|please (upload|take) a (clear|clearer)|retake the photo/i.test(s);
}

// Helper to clean base64 data
function sanitizeBase64(raw: string): { clean: string, mime: string } {
  let clean = (raw || '').trim();
  let mime = 'image/jpeg';
  const prefixMatch = clean.match(/^data:([^;]+);base64,/i);
  if (prefixMatch) {
    mime = prefixMatch[1];
    clean = clean.substring(prefixMatch[0].length);
  }
  clean = clean.replace(/[\r\n\s]+/g, '');
  return { clean, mime };
}

// Normalizes any prescription output format so mobile OCR never fails
// Concise Medicine Short Use strictly ending with "kelye" in Roman Urdu e.g. "Bukhar aur dard kelye", "Ulti aur matli kelye"
function getMedicineShortUse(name: string, generic?: string): string {
  const combined = `${name || ''} ${generic || ''}`.toLowerCase();

  // 1. Direct Brand & Salt Mappings (Strictly Roman Urdu ending with "... kelye")
  if (/panadol|paracetamol|calpol|febrol|disprol/i.test(combined)) return 'Bukhar aur dard kelye';
  if (/augmentin|amoxil|curam|klamoks|amoxicillin/i.test(combined)) return 'Infection ke ilaj kelye';
  if (/risek|omeprazole|omega|losec/i.test(combined)) return 'Maiday ki tezabiyat kelye';
  if (/nexum|esomeprazole|ezaday|eso\b/i.test(combined)) return 'Maiday ki jalan kelye';
  if (/brufen|ibuprofen|profen/i.test(combined)) return 'Dard aur sozish kelye';
  if (/ponstan|mefenamic/i.test(combined)) return 'Daant ke dard kelye';
  if (/disprin|aspirin|ascard|loprin/i.test(combined)) return 'Khoon patla karne kelye';
  if (/flagyl|metronidazole/i.test(combined)) return 'Pait ki kharabi kelye';
  if (/entamizole/i.test(combined)) return 'Pait ke maror kelye';
  if (/arinac|sinus|panadol cf|actifed/i.test(combined)) return 'Nazla aur zukam kelye';
  if (/rigix|zyrtec|softin|cetirizine|loratadine/i.test(combined)) return 'Allergy aur khujli kelye';
  if (/kestine|ebastine/i.test(combined)) return 'Mausami allergy kelye';
  if (/klaricid|clarithromycin/i.test(combined)) return 'Gale ke infection kelye';
  if (/ciproxin|novidat|ciprofloxacin/i.test(combined)) return 'Peshab ke infection kelye';
  if (/leflox|cravit|levofloxacin/i.test(combined)) return 'Sans ke infection kelye';
  if (/azomax|zithro|azithromycin/i.test(combined)) return 'Gale ki kharash kelye';
  if (/cefspan|caricef|cefixime/i.test(combined)) return 'Miyadi bukhar kelye';
  if (/ceftriaxone|rocephin|epiceph/i.test(combined)) return 'Shadeed bukhar kelye';
  if (/velosef|cephradine/i.test(combined)) return 'Zakham aur infection kelye';
  if (/ventolin|salbo|salbutamol|asthalin/i.test(combined)) return 'Dama aur saans kelye';
  if (/montiget|myteka|montelukast/i.test(combined)) return 'Dama aur allergy kelye';
  if (/hydryllin|pulmonol|acefyl|broncholate/i.test(combined)) return 'Balghami khansi kelye';
  if (/sancos|cophylac|corex|torex/i.test(combined)) return 'Khushk khansi kelye';
  if (/gravinate|dimenhydrinate|vomilux|motilium|domperidone/i.test(combined)) return 'Ulti aur matli kelye';
  if (/gaviscon|digene|mucaine|simeco/i.test(combined)) return 'Seene ki jalan kelye';
  if (/glucophage|neodipar|metformin/i.test(combined)) return 'Sugar control kelye';
  if (/amaryl|getryl|glimepiride/i.test(combined)) return 'Sugar control kelye';
  if (/januvia|sitagliptin|galvus|vildagliptin/i.test(combined)) return 'Sugar control kelye';
  if (/mixtard|lantus|humalog|insulin/i.test(combined)) return 'Sugar control kelye';
  if (/concor|bisoprolol|tenormin|atenolol/i.test(combined)) return 'Blood pressure kelye';
  if (/capoten|captopril|zestril|lisinopril/i.test(combined)) return 'Blood pressure kelye';
  if (/sofvasc|norvasc|amlodipine/i.test(combined)) return 'Blood pressure kelye';
  if (/exforge|co-diovan|valsartan/i.test(combined)) return 'Blood pressure kelye';
  if (/lipitor|x-plat|atorvastatin|rosuvastatin/i.test(combined)) return 'Cholesterol kam karne kelye';
  if (/surbex z|sangobion|theragran/i.test(combined)) return 'Jismi taqat kelye';
  if (/cac 1000|calcee|osteocare|osnate/i.test(combined)) return 'Haddiyon ki mazbooti kelye';
  if (/neurobion|mecobal|methycobal/i.test(combined)) return 'Aasabi dard kelye';
  if (/evion|vitamin e/i.test(combined)) return 'Jild aur balon kelye';
  if (/fefol|iberet|folic acid/i.test(combined)) return 'Khoon ki kami kelye';
  if (/spasler|no-spa|buscopan/i.test(combined)) return 'Pait ke dard kelye';
  if (/tanzo|tramal|tramadol/i.test(combined)) return 'Shadeed dard kelye';
  if (/synflex|naproxen/i.test(combined)) return 'Jodon ke dard kelye';
  if (/voltral|dicloran|diclofenac/i.test(combined)) return 'Dard aur sozish kelye';
  if (/polyfax|betnovate|fucidin|quench/i.test(combined)) return 'Zakham aur jild kelye';
  if (/dermovate|hydrocortisone/i.test(combined)) return 'Jild ki kharish kelye';
  if (/daktarin|canesten|clotrimazole/i.test(combined)) return 'Fungal infection kelye';
  if (/nilstat|nystatin/i.test(combined)) return 'Moonh ke chhalon kelye';
  if (/somogel|bonjela/i.test(combined)) return 'Moonh ke dard kelye';
  if (/tears naturale|refresh/i.test(combined)) return 'Aankhon ki khushki kelye';
  if (/betnesol|dexamethasone/i.test(combined)) return 'Shadeed allergy kelye';
  if (/lopamide|imodium|loperamide/i.test(combined)) return 'Dast aur motion kelye';
  if (/duphalac|lilac|lactulose/i.test(combined)) return 'Qabz door karne kelye';
  if (/ezivac|skilax/i.test(combined)) return 'Qabz kelye';

  // 2. Pharmacology Suffix Heuristics (Roman Urdu strictly ending with "... kelye")
  if (/prazole/i.test(combined)) return 'Maiday ki jalan kelye';
  if (/tidine/i.test(combined)) return 'Maiday ki gas kelye';
  if (/cillin/i.test(combined)) return 'Infection ke ilaj kelye';
  if (/oxacin/i.test(combined)) return 'Infection ke ilaj kelye';
  if (/mycin|micin/i.test(combined)) return 'Gale ke infection kelye';
  if (/cycline/i.test(combined)) return 'Infection ke ilaj kelye';
  if (/cefa|cefi|ceph/i.test(combined)) return 'Bukhar aur infection kelye';
  if (/statin/i.test(combined)) return 'Cholesterol control kelye';
  if (/sartan/i.test(combined)) return 'Blood pressure kelye';
  if (/olol/i.test(combined)) return 'Blood pressure kelye';
  if (/dipine/i.test(combined)) return 'Blood pressure kelye';
  if (/pril/i.test(combined)) return 'Blood pressure kelye';
  if (/formin/i.test(combined)) return 'Sugar control kelye';
  if (/gliptin/i.test(combined)) return 'Sugar control kelye';
  if (/glitazone/i.test(combined)) return 'Sugar control kelye';
  if (/fenac|profen/i.test(combined)) return 'Dard aur sozish kelye';
  if (/coxib/i.test(combined)) return 'Jodon ke dard kelye';
  if (/tirizine|tadine|astine/i.test(combined)) return 'Allergy aur khujli kelye';
  if (/lukast/i.test(combined)) return 'Dama aur allergy kelye';
  if (/butamol|terol/i.test(combined)) return 'Dama aur saans kelye';
  if (/conazole|fungin/i.test(combined)) return 'Fungal infection kelye';
  if (/sone|lone|onide/i.test(combined)) return 'Shadeed sozish kelye';
  if (/pram|xetine|line/i.test(combined)) return 'Zehni dabao kelye';
  if (/zepam|zolam/i.test(combined)) return 'Pur-sukoon neend kelye';
  if (/semide|thiazide/i.test(combined)) return 'Blood pressure kelye';

  if (generic && generic.trim().length > 2) {
    const cleanGen = generic.trim().split(/\s+/).slice(0, 2).join(' ');
    return `${cleanGen} kelye`;
  }
  return 'Dawai ke istemal kelye';
}

function normalizePrescriptionData(parsed: any) {
  if (!parsed) return null;
  let meds: any[] = [];
  if (Array.isArray(parsed)) {
    meds = parsed;
  } else if (Array.isArray(parsed.medicines)) {
    meds = parsed.medicines;
  } else if (Array.isArray(parsed.items)) {
    meds = parsed.items;
  } else if (Array.isArray(parsed.lineItems)) {
    meds = parsed.lineItems;
  } else if (Array.isArray(parsed.drugs)) {
    meds = parsed.drugs;
  } else if (Array.isArray(parsed.prescription)) {
    meds = parsed.prescription;
  } else if (Array.isArray(parsed.prescribedMedicines)) {
    meds = parsed.prescribedMedicines;
  } else if (Array.isArray(parsed.prescriptions)) {
    meds = parsed.prescriptions;
  } else if (Array.isArray(parsed.meds)) {
    meds = parsed.meds;
  } else if (Array.isArray(parsed.list)) {
    meds = parsed.list;
  } else if (parsed.medicines && typeof parsed.medicines === 'object') {
    meds = Object.values(parsed.medicines);
  } else if (parsed.data && typeof parsed.data === 'object') {
    return normalizePrescriptionData(parsed.data);
  }

  const cleanedMeds = meds
    .filter((m: any) => m && (m.name || m.medicine || m.brand || m.drug || m.item || m.medicineName))
    .filter((m: any) => {
      const nameStr = String(m.name || m.medicine || m.brand || m.drug || m.item || m.medicineName || '');
      return !isModelRefusal(nameStr);
    })
    .map((m: any) => {
      const name = String(m.name || m.medicine || m.brand || m.drug || m.item || m.medicineName || 'Prescribed Medicine').trim();
      const formula = String(m.formula || m.generic || m.salt || m.composition || '').trim();
      const rawUse = String(m.shortUse || m.use || m.purpose || m.indication || m.reason || '').trim();
      const shortUseHint = rawUse || getMedicineShortUse(name, formula);
      return {
        name,
        formula,
        form: String(m.form || m.type || 'Goli (Tablet)').trim(),
        timing: isModelRefusal(String(m.timing || '')) 
          ? 'Subah sham 1 goli khane ke baad (1+0+1)' 
          : String(m.timing || m.dosage || m.dose || m.schedule || m.frequency || 'Subah sham 1 goli khane ke baad (1+0+1)').trim(),
        usage: isModelRefusal(String(m.usage || '')) 
          ? 'Taza paani ke sath lein' 
          : String(m.usage || m.method || 'Taza paani ke sath lein').trim(),
        purpose: shortUseHint,
        shortUse: shortUseHint
      };
    });

  let rawAdvice = String(parsed.advice || parsed.precautions || parsed.instructions || '');
  if (!rawAdvice || isModelRefusal(rawAdvice)) {
    rawAdvice = 'Dawai hidayat ke mutabiq waqt par lein. Thandi, tali hui aur khatti cheezon se parhez karein aur saaf paani zyada piyen.';
  }

  let rawSummary = String(parsed.treatmentSummary || parsed.summary || parsed.treatment || '');
  if (!rawSummary || isModelRefusal(rawSummary)) {
    rawSummary = 'Nuskha ke mutabiq adviyaat aur ilaj ki mukammal tafseelat darj hain.';
  }

  let rawDoctor = '';
  if (typeof parsed.doctor === 'string') rawDoctor = parsed.doctor;
  else if (parsed.doctor && typeof parsed.doctor === 'object' && parsed.doctor.name) rawDoctor = parsed.doctor.name;
  else if (parsed.clinic) rawDoctor = String(parsed.clinic);
  else if (parsed.doctorName) rawDoctor = String(parsed.doctorName);
  if (!rawDoctor || isModelRefusal(rawDoctor) || /n\/a|not readable|unknown|mojood nahi/i.test(rawDoctor)) {
    rawDoctor = 'Doctor / Clinic Slip';
  }

  let rawPatient = '';
  if (typeof parsed.patient === 'string') rawPatient = parsed.patient;
  else if (parsed.patient && typeof parsed.patient === 'object' && parsed.patient.name) rawPatient = parsed.patient.name;
  else if (parsed.patientName) rawPatient = String(parsed.patientName);
  if (!rawPatient || isModelRefusal(rawPatient) || /n\/a|not readable|unknown|mojood nahi/i.test(rawPatient)) {
    rawPatient = 'General Patient';
  }

  return {
    doctor: rawDoctor,
    patient: rawPatient,
    treatmentSummary: rawSummary,
    advice: rawAdvice,
    medicines: cleanedMeds
  };
}

// Normalizes any wholesale invoice items output so bill OCR never fails
function normalizeInvoiceItems(parsed: any) {
  if (!parsed) return [];
  let list: any[] = [];
  if (Array.isArray(parsed)) {
    list = parsed;
  } else if (Array.isArray(parsed.lineItems)) {
    list = parsed.lineItems;
  } else if (Array.isArray(parsed.items)) {
    list = parsed.items;
  } else if (Array.isArray(parsed.medicines)) {
    list = parsed.medicines;
  } else if (Array.isArray(parsed.invoicedItems)) {
    list = parsed.invoicedItems;
  } else if (Array.isArray(parsed.invoiceItems)) {
    list = parsed.invoiceItems;
  } else if (Array.isArray(parsed.lines)) {
    list = parsed.lines;
  } else if (Array.isArray(parsed.products)) {
    list = parsed.products;
  } else if (Array.isArray(parsed.rows)) {
    list = parsed.rows;
  } else if (Array.isArray(parsed.table)) {
    list = parsed.table;
  } else if (Array.isArray(parsed.billItems)) {
    list = parsed.billItems;
  } else if (parsed.data && typeof parsed.data === 'object') {
    return normalizeInvoiceItems(parsed.data);
  }

  const detectedDist = String(parsed.distributorName || parsed.distributor || parsed.supplier || parsed.vendor || '').trim();

  return list.filter((item: any) => item && (item.name || item.itemName || item.item || item.description || item.medicine || item.product) && !isModelRefusal(String(item.name || item.item))).map((item: any) => ({
    name: String(item.name || item.itemName || item.item || item.description || item.medicine || item.product || 'Medicine Item').trim(),
    generic: String(item.generic || item.formula || '').trim(),
    batch: String(item.batch || item.batch_no || item.batchNo || item.batchNumber || 'B-01').trim(),
    expiry: String(item.expiry || item.exp || '2027-12').trim(),
    packSize: String(item.packSize || item.pack_size || item.pack || '20').trim(),
    qty: Number(item.qty || item.quantity || item.packs || item.count || 1) || 1,
    buyRate: Number(item.buyRate || item.rate || item.tradePrice || item.tp || item.price || item.unitPrice || 0) || 0,
    distributor: String(item.distributor || item.supplier || detectedDist || 'Wholesale Distributor').trim(),
    mrp: ''
  }));
}

// Fallback line parser if model returns formatted text/markdown instead of JSON
function extractMedicinesFromTextLines(text: string) {
  if (!text || typeof text !== 'string') return [];
  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  const meds: any[] = [];
  for (const line of lines) {
    const clean = line.replace(/^[\*\-\d\.\)\s]+/, '').trim();
    if (clean.length < 3 || isModelRefusal(clean)) continue;
    if (/^(rx|doctor|patient|clinic|date|advice|note|diagnosis|sig|treatment|name|instructions|summary|findings):/i.test(clean)) continue;
    if (/(tab|cap|syp|inj|drop|goli|capsule|mg|ml|gm|sachet|syrup|tablet|ointment|cream)/i.test(clean) || clean.split(/\s+/).length >= 1) {
      const parts = clean.split(/[-–—:]/);
      const name = parts[0].trim().replace(/^[\*\#_]+|[\*\#_]+$/g, '');
      if (name.length >= 2 && !isModelRefusal(name)) {
        const timing = parts[1]?.trim().replace(/^[\*\#_]+|[\*\#_]+$/g, '') || 'Subah sham 1 goli khane ke baad (1+0+1)';
        const shortUseHint = getMedicineShortUse(name, '');
        meds.push({
          name,
          formula: '',
          form: /syp|syrup/i.test(name) ? 'Sharbath (Syrup)' : (/cap/i.test(name) ? 'Capsule' : (/inj/i.test(name) ? 'Injection' : (/drop/i.test(name) ? 'Drops' : 'Goli (Tablet)'))),
          timing,
          usage: 'Taza paani ke sath lein',
          purpose: shortUseHint,
          shortUse: shortUseHint
        });
      }
    }
  }
  return meds;
}

function extractInvoiceItemsFromTextLines(text: string) {
  if (!text || typeof text !== 'string') return [];
  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  const items: any[] = [];
  for (const line of lines) {
    const clean = line.replace(/^[\*\-\d\.\)\s]+/, '').trim();
    if (clean.length < 3 || isModelRefusal(clean)) continue;
    if (/^(invoice|bill|date|total|subtotal|distributor|supplier|customer|terms|ntn|strn|discount|gst):/i.test(clean)) continue;
    const parts = clean.split(/[|,;\t]/).map(p => p.trim()).filter(Boolean);
    if (parts.length >= 2) {
      const name = parts[0].replace(/^[\*\#_]+|[\*\#_]+$/g, '');
      const rateCandidate = Number(parts.find(p => /^\d+(\.\d+)?$/.test(p))) || 0;
      if (name.length >= 2) {
        items.push({
          name,
          generic: '',
          batch: 'B-01',
          expiry: '2027-12',
          packSize: '20',
          qty: 1,
          buyRate: rateCandidate,
          distributor: 'Wholesale Distributor',
          mrp: ''
        });
      }
    } else {
      const numMatch = clean.match(/^([a-zA-Z0-9\s\+\-\/\.]{3,35})\s*(?:.*?(\d+(?:\.\d+)?))?/);
      if (numMatch && numMatch[1]) {
        items.push({
          name: numMatch[1].trim(),
          generic: '',
          batch: 'B-01',
          expiry: '2027-12',
          packSize: '20',
          qty: 1,
          buyRate: Number(numMatch[2]) || 0,
          distributor: 'Wholesale Distributor',
          mrp: ''
        });
      }
    }
  }
  return items;
}

// Initialize Gemini with accurate real vision scanning and multi-model retries
async function generateWithVisionFallback(
  prompt: string, 
  imageBase64: string
): Promise<string | null> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is missing from environment.');
    return null;
  }

  const ai = new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build'
      }
    }
  });

  const { clean, mime } = sanitizeBase64(imageBase64);
  // Comprehensive Gemini Multimodal Vision Cascade (Official, high-performing multimodal models)
  const models = [
    'gemini-3.1-flash-lite',
    'gemini-flash-latest',
    'gemini-3.8-flash'
  ];

  let bestParsedFallback: string | null = null;

  for (const modelName of models) {
    try {
      console.log(`Analyzing document with vision model: ${modelName}...`);
      const apiCall = ai.models.generateContent({
        model: modelName,
        contents: [
          {
            inlineData: {
              mimeType: mime || 'image/jpeg',
              data: clean
            }
          },
          {
            text: prompt
          }
        ]
      });

      const timeoutCall = new Promise<never>((_, reject) => 
        setTimeout(() => reject(new Error(`Model ${modelName} timeout`)), 25000)
      );

      const response: any = await Promise.race([apiCall, timeoutCall]);

      if (response && response.text) {
        console.log(`Received response from ${modelName} (${response.text.length} chars).`);
        const parsed = extractJsonFromText(response.text);
        if (parsed) {
          const hasItems = (Array.isArray(parsed) && parsed.length > 0) ||
                           (Array.isArray(parsed.medicines) && parsed.medicines.length > 0) ||
                           (Array.isArray(parsed.items) && parsed.items.length > 0) ||
                           (Array.isArray(parsed.lineItems) && parsed.lineItems.length > 0) ||
                           (Array.isArray(parsed.lines) && parsed.lines.length > 0) ||
                           (Array.isArray(parsed.drugs) && parsed.drugs.length > 0) ||
                           (Array.isArray(parsed.products) && parsed.products.length > 0) ||
                           (Array.isArray(parsed.rows) && parsed.rows.length > 0) ||
                           (Array.isArray(parsed.table) && parsed.table.length > 0) ||
                           (Array.isArray(parsed.prescription) && parsed.prescription.length > 0);
          if (hasItems) {
            console.log(`Vision success on model ${modelName} with detected items.`);
            return response.text;
          }
          if (!bestParsedFallback) {
            bestParsedFallback = response.text;
          }
        } else if (response.text.length > 20) {
          if (!bestParsedFallback) {
            bestParsedFallback = response.text;
          }
        }
      }
    } catch (err: any) {
      console.warn(`Vision model ${modelName} warning:`, err?.message || err);
      // Seamlessly advance to next model in cascade
    }
  }

  return bestParsedFallback;
}

// -------------------------------------------------------------
// AI Prescription Scanner Endpoint
// -------------------------------------------------------------
app.post('/api/ai/scan-prescription', async (req: Request, res: Response): Promise<void> => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) {
      res.status(400).json({ success: false, error: 'Image data darkar hai.' });
      return;
    }

    const prompt = `Carefully read this prescription slip, clinic pad, hospital note, or doctor handwriting photo.
Transcribe every medicine written on the paper: brand or generic name, strength, and dosage instructions.
For each medicine detected, determine its medical clinical use in Roman Urdu ending with "kelye" (for example: "Bukhar aur dard kelye", "Ulti aur matli kelye", "Maiday ki tezabiyat kelye", "Khansi kelye", "Infection kelye", "Allergy kelye", "Sugar control kelye", "Blood pressure kelye", "Dard aur sozish kelye").
Also read doctor name, clinic name, and patient name if written.

Return JSON format:
{
  "doctor": "Doctor / Clinic name",
  "patient": "Patient name",
  "treatmentSummary": "Short diagnosis or summary",
  "advice": "Precautions in Roman Urdu",
  "medicines": [
    {
      "name": "Medicine name and strength",
      "formula": "Generic salt if visible",
      "form": "Goli/Capsule/Syrup/Drops/Injection",
      "timing": "Dosage instructions e.g. Subah sham 1 goli (1+0+1)",
      "usage": "Usage instructions e.g. Taza paani ke sath lein",
      "shortUse": "Purpose in Roman Urdu ending with kelye"
    }
  ]
}`;

    const text = await generateWithVisionFallback(prompt, imageBase64);
    const parsed = text ? extractJsonFromText(text) : null;
    let normalized = normalizePrescriptionData(parsed);

    // Fallback: extract medicines from lines if JSON parsing didn't find any
    if (!normalized || !normalized.medicines || normalized.medicines.length === 0) {
      if (text) {
        const lineMeds = extractMedicinesFromTextLines(text);
        if (lineMeds.length > 0) {
          normalized = {
            doctor: normalized?.doctor || 'Doctor / Clinic Slip',
            patient: normalized?.patient || 'General Patient',
            treatmentSummary: normalized?.treatmentSummary || 'Nuskha ke mutabiq adviyaat darj zail hain.',
            advice: normalized?.advice || 'Dawai hidayat ke mutabiq waqt par lein.',
            medicines: lineMeds
          };
        }
      }
    }

    if (normalized && normalized.medicines && normalized.medicines.length > 0) {
      res.json({
        success: true,
        data: normalized
      });
      return;
    }

    if (text) {
      res.json({
        success: true,
        data: normalized || {
          doctor: 'Doctor / Clinic Slip',
          patient: 'General Patient',
          treatmentSummary: '',
          advice: 'Dawai hidayat ke mutabiq waqt par lein.',
          medicines: []
        }
      });
      return;
    }

    res.status(502).json({
      success: false,
      error: 'AI Scanner connect nahi ho saka. Barah-e-karam internet connection check karein ya dobara koshish karein.'
    });
  } catch (err: any) {
    console.error('Prescription OCR server error:', err);
    res.status(500).json({
      success: false,
      error: err?.message || 'Prescription scan mein masla aya.'
    });
  }
});

// -------------------------------------------------------------
// AI Wholesale Invoice Scanner Endpoint
// -------------------------------------------------------------
app.post('/api/ai/scan-invoice', async (req: Request, res: Response): Promise<void> => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) {
      res.status(400).json({ success: false, error: 'Image data darkar hai.' });
      return;
    }

    const prompt = `You are an expert pharmacy wholesale bill and distributor invoice OCR reader.
Examine this invoice, delivery challan, or receipt slip.
Transcribe every medicine or item row printed on the bill:
- name: product name and strength as printed
- batch: batch number if visible
- qty: invoiced quantity of packs (number)
- buyRate: wholesale buy rate (TP) per pack (number)
- expiry: expiry date (YYYY-MM) if visible
- distributor: distributor / supplier name from bill header

Return JSON format:
{
  "distributorName": "Distributor or Supplier name",
  "lineItems": [
    {
      "name": "Medicine name and strength",
      "batch": "Batch number",
      "qty": 10,
      "buyRate": 150.00,
      "expiry": "YYYY-MM"
    }
  ]
}`;

    const text = await generateWithVisionFallback(prompt, imageBase64);
    const parsed = text ? extractJsonFromText(text) : null;
    let items = normalizeInvoiceItems(parsed);

    // Fallback: extract items from lines if JSON parsing missed them
    if (items.length === 0 && text) {
      items = extractInvoiceItemsFromTextLines(text);
    }

    if (items.length > 0) {
      res.json({ success: true, data: items });
      return;
    }

    if (text) {
      res.json({ success: true, data: [] });
      return;
    }

    res.status(502).json({
      success: false,
      error: 'AI Invoice Scanner connect nahi ho saka. Barah-e-karam dobara koshish karein.'
    });
  } catch (err: any) {
    console.error('Invoice OCR server error:', err);
    res.status(500).json({
      success: false,
      error: err?.message || 'Invoice scan mein masla aya.'
    });
  }
});

// -------------------------------------------------------------
// AI Wholesale Margin & Bonus Scheme Scanner Endpoint
// -------------------------------------------------------------
app.post('/api/ai/scan-margin', async (req: Request, res: Response): Promise<void> => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) {
      res.status(400).json({ success: false, error: 'Image data darkar hai.' });
      return;
    }

    const prompt = `Inspect this wholesale bill or scheme slip.
Read all printed medicine items, invoiced wholesale buy rates (TP), quantities, and any free bonus packs received (e.g. 10+1 or 5+1 scheme).

Return JSON format:
[
  {
    "name": "Medicine name and strength",
    "buyRate": 150,
    "qty": 10,
    "freeQty": 1
  }
]`;

    const text = await generateWithVisionFallback(prompt, imageBase64);
    const parsed = text ? extractJsonFromText(text) : null;
    let items: any[] = [];
    if (Array.isArray(parsed)) items = parsed;
    else if (Array.isArray(parsed?.items)) items = parsed.items;
    else if (Array.isArray(parsed?.medicines)) items = parsed.medicines;
    else if (Array.isArray(parsed?.lineItems)) items = parsed.lineItems;

    if (items.length === 0 && text) {
      const lineItems = extractInvoiceItemsFromTextLines(text);
      items = lineItems.map(i => ({
        name: i.name,
        buyRate: i.buyRate,
        qty: i.qty,
        freeQty: 0
      }));
    }

    const cleanItems = items.filter(i => i && i.name && !isModelRefusal(String(i.name))).map((item) => ({
      name: String(item.name).trim(),
      buyRate: Number(item.buyRate || item.rate) || 0,
      qty: Number(item.qty || item.quantity) || 1,
      freeQty: Number(item.freeQty || item.free) || 0,
      mrp: ''
    }));

    if (cleanItems.length > 0) {
      res.json({
        success: true,
        data: cleanItems
      });
      return;
    }

    if (text) {
      res.json({
        success: true,
        data: []
      });
      return;
    }

    res.status(502).json({
      success: false,
      error: 'AI Margin Scanner connect nahi ho saka. Barah-e-karam dobara koshish karein.'
    });
  } catch (err: any) {
    console.error('Margin OCR server error:', err);
    res.status(500).json({
      success: false,
      error: err?.message || 'Margin scan mein masla aya.'
    });
  }
});

// -------------------------------------------------------------
// AI Medicine Packaging / Strip / Box Scanner (Direct Stock In)
// -------------------------------------------------------------
app.post('/api/ai/scan-medicine-pack', async (req: Request, res: Response): Promise<void> => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) {
      res.status(400).json({ success: false, error: 'Image data darkar hai.' });
      return;
    }

    const packSystemInstruction = `You are an expert Clinical Pharmacist and forensic pharmaceutical packaging reader.
Examine this mobile photograph of a medicine box, blister pack, strip, ampoule, vial, syrup bottle, or dropper.
Read the actual printed text on the packaging carefully even with glare, mobile phone angle, or low lighting.
STRICT ZERO-HALLUCINATION RULE:
Extract ONLY what is physically printed on this packaging. DO NOT guess or substitute with other medicines.
Identify:
1. Brand Name and Strength (e.g. "Panadol Extra", "Augmentin 625mg", "Flygyl 400mg", "Arinac Forte")
2. Generic Salt / Formula (e.g. "Paracetamol + Caffeine", "Co-Amoxiclav", "Ibuprofen + Pseudoephedrine")
3. Form / Type (e.g. "Tablet", "Capsule", "Syrup", "Injection", "Drops", "Sachet", "Ointment")
4. Pack Size (e.g. "20", "10", "1x10", "60ml")
5. Batch Number if printed (e.g. "B104", "L982")
6. Expiry Date (extract month MM e.g. "12" and year YY e.g. "28" or "2028")
7. Retail MRP price (Rs.) if printed
8. Trade TP Price (Rs.) if printed`;

    const prompt = `Read this medicine packaging / strip / box image with high precision.
Extract the exact medicine brand name, formula, pack size, batch number, expiry date, and printed retail MRP.
Never output refusal notes; return valid JSON adhering to schema.`;

    const packSchema = {
      type: Type.OBJECT,
      properties: {
        name: { type: Type.STRING, description: 'Brand name with strength e.g. Augmentin 625mg' },
        generic: { type: Type.STRING, description: 'Generic formula / active ingredients' },
        form: { type: Type.STRING, description: 'Form e.g. tab, cap, syp, drop, inj, scht' },
        packSize: { type: Type.STRING, description: 'Pack size e.g. 20 or 10x10' },
        batch: { type: Type.STRING, description: 'Batch number' },
        expiryMonth: { type: Type.STRING, description: 'Expiry month 01 to 12' },
        expiryYear: { type: Type.STRING, description: 'Expiry year 2026 to 2035 or 26 to 35' },
        mrp: { type: Type.NUMBER, description: 'Printed retail MRP price' },
        buyRate: { type: Type.NUMBER, description: 'Printed trade TP price if visible' }
      },
      required: ['name']
    };

    const text = await generateWithVisionFallback(prompt, imageBase64);
    const parsed = text ? extractJsonFromText(text) : null;

    const targetObj = Array.isArray(parsed) ? parsed[0] : (parsed?.medicine || parsed?.item || parsed?.data || parsed || {});
    const extractedName = String(targetObj.name || targetObj.brand || targetObj.brandName || targetObj.medicineName || targetObj.title || targetObj.product || targetObj.productName || targetObj.description || '').trim();

    if (extractedName && !isModelRefusal(extractedName)) {
      res.json({
        success: true,
        data: {
          name: extractedName,
          generic: String(targetObj.generic || targetObj.formula || '').trim(),
          form: String(targetObj.form || 'tab').toLowerCase(),
          packSize: String(targetObj.packSize || targetObj.pack || '20').trim(),
          batch: String(targetObj.batch || targetObj.batchNo || '').trim(),
          expiryMonth: String(targetObj.expiryMonth || targetObj.expMonth || '').padStart(2, '0').slice(-2),
          expiryYear: String(targetObj.expiryYear || targetObj.expYear || '').slice(-2),
          mrp: Number(targetObj.mrp || targetObj.retailPrice || targetObj.price) || 0,
          buyRate: Number(targetObj.buyRate || targetObj.tp || targetObj.tradePrice) || 0
        }
      });
      return;
    }

    res.json({
      success: false,
      error: 'Medicine packaging se dawa ka naam detect nahi ho saka.'
    });
  } catch (err: any) {
    console.error('Packaging OCR error:', err);
    res.status(500).json({ success: false, error: 'Packaging OCR fail ho gaya' });
  }
});

// -------------------------------------------------------------
// Live Connected Network Pharmacies Central Registry
// -------------------------------------------------------------
interface NetworkPharmacy {
  id: string;
  name: string;
  ownerName?: string;
  city: string;
  phone: string;
  email?: string;
  licenseNo?: string;
  remarks?: string;
  updatedAt: string;
}

const NETWORK_FILE = path.resolve(__dirname, 'network_pharmacies.json');

function loadNetworkPharmacies(): NetworkPharmacy[] {
  try {
    if (fs.existsSync(NETWORK_FILE)) {
      const data = fs.readFileSync(NETWORK_FILE, 'utf-8');
      const parsed = JSON.parse(data);
      if (Array.isArray(parsed)) {
        // Filter out any stale mock entries if they exist
        return parsed.filter(p => !['net_1', 'net_2', 'net_3'].includes(p.id) && !['Al-Madina Pharmacy', 'Qadri Medicos & Chemists', 'Bismillah Medical & General Store'].includes(p.name));
      }
    }
  } catch (e) {
    console.error('Error reading network pharmacies file:', e);
  }
  return [];
}

function saveNetworkPharmacies(list: NetworkPharmacy[]) {
  try {
    fs.writeFileSync(NETWORK_FILE, JSON.stringify(list, null, 2), 'utf-8');
  } catch (e) {
    console.error('Error saving network pharmacies file:', e);
  }
}

let activeNetworkPharmacies = loadNetworkPharmacies();

app.get('/api/network/pharmacies', (_req: Request, res: Response) => {
  res.json({
    success: true,
    count: activeNetworkPharmacies.length,
    pharmacies: activeNetworkPharmacies
  });
});

app.post('/api/network/register', (req: Request, res: Response): void => {
  try {
    const { name, ownerName, city, phone, email, licenseNo, remarks } = req.body;
    if (!name || !city || !phone) {
      res.status(400).json({ success: false, error: 'Pharmacy Name, City aur Phone zaroori hain.' });
      return;
    }

    const cleanPhone = String(phone).trim();
    const cleanName = String(name).trim();
    const cleanCity = String(city).trim();
    const cleanEmail = email ? String(email).trim().toLowerCase() : '';

    // Check if store already registered by email, phone, or name
    const existingIndex = activeNetworkPharmacies.findIndex(p => 
      (cleanEmail && p.email && p.email.toLowerCase() === cleanEmail) ||
      (p.phone && p.phone.replace(/\D/g, '') === cleanPhone.replace(/\D/g, '')) ||
      (p.name.toLowerCase() === cleanName.toLowerCase() && p.city.toLowerCase() === cleanCity.toLowerCase())
    );

    const record: NetworkPharmacy = {
      id: existingIndex !== -1 ? activeNetworkPharmacies[existingIndex].id : ('net_' + Date.now()),
      name: cleanName,
      ownerName: (ownerName || '').trim() || (cleanEmail ? cleanEmail.split('@')[0] : 'Store Owner'),
      city: cleanCity,
      phone: cleanPhone,
      email: cleanEmail,
      licenseNo: (licenseNo || '').trim(),
      remarks: (remarks || 'Active Digital Pharma Connected Pharmacy').trim(),
      updatedAt: new Date().toISOString()
    };

    if (existingIndex !== -1) {
      activeNetworkPharmacies[existingIndex] = record;
    } else {
      activeNetworkPharmacies.unshift(record);
    }

    saveNetworkPharmacies(activeNetworkPharmacies);

    res.json({
      success: true,
      message: `${cleanName} successfully registered in Digital Pharma Network!`,
      pharmacy: record,
      totalConnected: activeNetworkPharmacies.length
    });
  } catch (err: any) {
    console.error('Network registration error:', err);
    res.status(500).json({ success: false, error: 'Network registration failed' });
  }
});

app.post('/api/network/unregister', (req: Request, res: Response): void => {
  try {
    const { id, email, phone } = req.body;
    activeNetworkPharmacies = activeNetworkPharmacies.filter(p => {
      if (id && p.id === id) return false;
      if (email && p.email && p.email.toLowerCase() === String(email).toLowerCase()) return false;
      if (phone && p.phone && p.phone.replace(/\D/g, '') === String(phone).replace(/\D/g, '')) return false;
      return true;
    });
    saveNetworkPharmacies(activeNetworkPharmacies);
    res.json({ success: true, count: activeNetworkPharmacies.length });
  } catch (e) {
    res.status(500).json({ success: false, error: 'Unregister failed' });
  }
});

// Health check
app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', app: 'Digital Pharma', developer: '@ShahzadKhakh' });
});

// Setup Vite middleware in dev or static files in production
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.resolve(__dirname, 'dist');
    app.use(express.static(distPath, {
      setHeaders: (res, filePath) => {
        if (filePath.endsWith('.html')) {
          res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
        }
      }
    }));
    app.get('*', (_req, res) => {
      res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
      res.sendFile(path.resolve(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Digital Pharma Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
