import express, { Request, Response } from 'express';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { GoogleGenAI, Type } from '@google/genai';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = Number(process.env.PORT) || 3000;

// Enable CORS for all origins (allowing GitHub Pages and mobile web to call AI endpoints)
app.use((_req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With, Accept, Origin');
  if (_req.method === 'OPTIONS') {
    res.sendStatus(200);
    return;
  }
  next();
});

// High body limit to allow image uploads from high-resolution phone cameras
app.use(express.json({ limit: '35mb' }));
app.use(express.urlencoded({ limit: '35mb', extended: true }));

const APP_BUILD_TIMESTAMP = 'dp-build-' + Date.now();

// Static PWA & Asset routes with strict freshness headers
app.get('/manifest.json', (_req, res) => {
  res.setHeader('Content-Type', 'application/manifest+json');
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');
  res.sendFile(path.resolve(__dirname, 'public/manifest.json'));
});
app.get('/sw.js', (_req, res) => {
  res.setHeader('Content-Type', 'application/javascript');
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');
  res.setHeader('Service-Worker-Allowed', '/');
  res.sendFile(path.resolve(__dirname, 'public/sw.js'));
});
app.get('/icon.svg', (_req, res) => {
  res.setHeader('Content-Type', 'image/svg+xml');
  res.setHeader('Cache-Control', 'public, max-age=86400');
  res.sendFile(path.resolve(__dirname, 'public/icon.svg'));
});

// Real-time app version check for seamless live PWA updates without reinstalling
app.get('/api/app-version', (_req, res) => {
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');
  res.json({
    version: APP_BUILD_TIMESTAMP,
    timestamp: Date.now(),
    app: 'Digital Pharma',
    status: 'live-sync'
  });
});

// Helper to extract JSON from Gemini text output
function extractJsonFromText(rawText: string): any {
  if (!rawText) return null;
  const cleaned = rawText.replace(/```json/gi, '').replace(/```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    // Try finding array
    const sArr = cleaned.indexOf('[');
    const eArr = cleaned.lastIndexOf(']');
    if (sArr !== -1 && eArr > sArr) {
      try {
        const candidate = cleaned.substring(sArr, eArr + 1).replace(/,\s*([}\]])/g, '$1');
        return JSON.parse(candidate);
      } catch (err) {}
    }
    // Try finding object
    const sObj = cleaned.indexOf('{');
    const eObj = cleaned.lastIndexOf('}');
    if (sObj !== -1 && eObj > sObj) {
      try {
        const candidate = cleaned.substring(sObj, eObj + 1).replace(/,\s*([}\]])/g, '$1');
        return JSON.parse(candidate);
      } catch (err) {}
    }
  }
  return null;
}

// Regex to catch actual refusal sentences generated by vision models without blocking real medicines
function isModelRefusal(str: string): boolean {
  if (!str || typeof str !== 'string') return false;
  const s = str.trim().toLowerCase();
  // Don't flag actual medicines like "Claritek", "Clear Eyes", etc.
  if (s.length < 20) return false;
  return /tasveer.*(roshni|dubara|saf|wazeh|dhundli|dobara)|tasvir.*(roshni|dubara)|cannot read|unable to read|unreadable image|please (upload|take) a (clear|clearer)|retake the photo/i.test(s);
}

// Helper to clean base64 data
function sanitizeBase64(raw: string): { clean: string, mime: string } {
  let clean = (raw || '').trim();
  let mime = 'image/jpeg';
  const prefixMatch = clean.match(/^data:([^;]+);base64,/i);
  if (prefixMatch) {
    mime = prefixMatch[1];
    clean = clean.substring(prefixMatch[0].length);
  }
  clean = clean.replace(/[\r\n\s]+/g, '');
  return { clean, mime };
}

// Normalizes any prescription output format so mobile OCR never fails
// Concise Medicine Short Use (Strictly 3-4 words in Roman Urdu, Zero Headings/Pill Prefixes)
function getMedicineShortUse(name: string, generic?: string): string {
  const combined = `${name || ''} ${generic || ''}`.toLowerCase();

  // 1. Direct Brand & Salt Mappings (Strictly 3 to 4 words)
  if (/panadol|paracetamol|calpol|febrol|disprol/i.test(combined)) return 'Dard aur Bukhar';
  if (/augmentin|amoxil|curam|klamoks|amoxicillin/i.test(combined)) return 'Bacterial Infection Ilaj';
  if (/risek|omeprazole|omega|losec/i.test(combined)) return 'Maiday ki Tezabiyat';
  if (/nexum|esomeprazole|ezaday|eso\b/i.test(combined)) return 'Maida Jalan Ulcer';
  if (/brufen|ibuprofen|profen/i.test(combined)) return 'Dard aur Sozish';
  if (/ponstan|mefenamic/i.test(combined)) return 'Daant Mahwari Dard';
  if (/disprin|aspirin|ascard|loprin/i.test(combined)) return 'Khoon Patla Dil Hifazat';
  if (/flagyl|metronidazole/i.test(combined)) return 'Pait Kharab Dast';
  if (/entamizole/i.test(combined)) return 'Pait Maror Pechish';
  if (/arinac|sinus|panadol cf|actifed/i.test(combined)) return 'Nazla Zukam Band Naak';
  if (/rigix|zyrtec|softin|cetirizine|loratadine/i.test(combined)) return 'Allergy Khujli Cheenkain';
  if (/kestine|ebastine/i.test(combined)) return 'Mausami Allergy Zukam';
  if (/klaricid|clarithromycin/i.test(combined)) return 'Gala Sans Infection';
  if (/ciproxin|novidat|ciprofloxacin/i.test(combined)) return 'Peshab Pait Infection';
  if (/leflox|cravit|levofloxacin/i.test(combined)) return 'Sans Phephray Infection';
  if (/azomax|zithro|azithromycin/i.test(combined)) return 'Gala Kharash Tonsils';
  if (/cefspan|caricef|cefixime/i.test(combined)) return 'Miyadi Bukhar Infection';
  if (/ceftriaxone|rocephin|epiceph/i.test(combined)) return 'Shadeed Bukhar Infection';
  if (/velosef|cephradine/i.test(combined)) return 'Zakham Jild Infection';
  if (/ventolin|salbo|salbutamol|asthalin/i.test(combined)) return 'Dama Sans Tangi';
  if (/montiget|myteka|montelukast/i.test(combined)) return 'Dama Mausami Allergy';
  if (/hydryllin|pulmonol|acefyl|broncholate/i.test(combined)) return 'Balgham Khansi Aaram';
  if (/sancos|cophylac|corex|torex/i.test(combined)) return 'Khushk Khansi Gala';
  if (/gravinate|dimenhydrinate|vomilux|motilium|domperidone/i.test(combined)) return 'Ulti Matli Bechaini';
  if (/gaviscon|digene|mucaine|simeco/i.test(combined)) return 'Seene Jalan Tezabiyat';
  if (/glucophage|neodipar|metformin/i.test(combined)) return 'Sugar Diabetes Control';
  if (/amaryl|getryl|glimepiride/i.test(combined)) return 'Khoon Sugar Control';
  if (/januvia|sitagliptin|galvus|vildagliptin/i.test(combined)) return 'Sugar Kam Karne Wali';
  if (/mixtard|lantus|humalog|insulin/i.test(combined)) return 'Sugar Control Teeka';
  if (/concor|bisoprolol|tenormin|atenolol/i.test(combined)) return 'Blood Pressure Dil Dharkan';
  if (/capoten|captopril|zestril|lisinopril/i.test(combined)) return 'High Blood Pressure Control';
  if (/sofvasc|norvasc|amlodipine/i.test(combined)) return 'Blood Pressure Angina';
  if (/exforge|co-diovan|valsartan/i.test(combined)) return 'Ziddi Blood Pressure';
  if (/lipitor|x-plat|atorvastatin|rosuvastatin/i.test(combined)) return 'Cholesterol Charbi Kami';
  if (/surbex z|sangobion|theragran/i.test(combined)) return 'Taqat Jismi Kamzori';
  if (/cac 1000|calcee|osteocare|osnate/i.test(combined)) return 'Haddiyon Mazbooti Calcium';
  if (/neurobion|mecobal|methycobal/i.test(combined)) return 'Patthon Asabi Dard';
  if (/evion|vitamin e/i.test(combined)) return 'Jild Balon Taqat';
  if (/fefol|iberet|folic acid/i.test(combined)) return 'Khoon Kami Hamal Taqat';
  if (/spasler|no-spa|buscopan/i.test(combined)) return 'Pait Maror Kheenchaao';
  if (/tanzo|tramal|tramadol/i.test(combined)) return 'Shadeed Dard Aaram';
  if (/synflex|naproxen/i.test(combined)) return 'Joron Pathon Dard';
  if (/voltral|dicloran|diclofenac/i.test(combined)) return 'Jism Dard Sozish';
  if (/polyfax|betnovate|fucidin|quench/i.test(combined)) return 'Zakham Jild Sozish';
  if (/dermovate|hydrocortisone/i.test(combined)) return 'Jild Khujli Eczema';
  if (/daktarin|canesten|clotrimazole/i.test(combined)) return 'Fungal Infection Daad';
  if (/nilstat|nystatin/i.test(combined)) return 'Moonh Chhalay Infection';
  if (/somogel|bonjela/i.test(combined)) return 'Moonh Chhalon Dard';
  if (/tears naturale|refresh/i.test(combined)) return 'Aankhon Khushki Jalan';
  if (/betnesol|dexamethasone/i.test(combined)) return 'Shadeed Allergy Sozish';
  if (/lopamide|imodium|loperamide/i.test(combined)) return 'Dast Pechish Rokna';
  if (/duphalac|lilac|lactulose/i.test(combined)) return 'Qabz Door Karna';
  if (/ezivac|skilax/i.test(combined)) return 'Daimi Qabz Dawa';

  // 2. Pharmacology Suffix Heuristics (Strictly 3 to 4 words)
  if (/prazole/i.test(combined)) return 'Maiday Jalan Tezabiyat';
  if (/tidine/i.test(combined)) return 'Maida Gas Tezabiyat';
  if (/cillin/i.test(combined)) return 'Bacterial Infection Ilaj';
  if (/oxacin/i.test(combined)) return 'Peshab Sans Infection';
  if (/mycin|micin/i.test(combined)) return 'Gala Sans Infection';
  if (/cycline/i.test(combined)) return 'Infection Chehray Danay';
  if (/cefa|cefi|ceph/i.test(combined)) return 'Bukhar Bacterial Infection';
  if (/statin/i.test(combined)) return 'Cholesterol Charbi Kami';
  if (/sartan/i.test(combined)) return 'Blood Pressure Control';
  if (/olol/i.test(combined)) return 'Blood Pressure Dil Dharkan';
  if (/dipine/i.test(combined)) return 'Blood Pressure Angina';
  if (/pril/i.test(combined)) return 'Blood Pressure Hifazat';
  if (/formin/i.test(combined)) return 'Sugar Diabetes Control';
  if (/gliptin/i.test(combined)) return 'Sugar Control Ilaj';
  if (/glitazone/i.test(combined)) return 'Sugar Control Ilaj';
  if (/fenac|profen/i.test(combined)) return 'Dard Sozish Aaram';
  if (/coxib/i.test(combined)) return 'Joron Dard Sozish';
  if (/tirizine|tadine|astine/i.test(combined)) return 'Allergy Khujli Cheenkain';
  if (/lukast/i.test(combined)) return 'Dama Mausami Allergy';
  if (/butamol|terol/i.test(combined)) return 'Dama Sans Tangi';
  if (/conazole|fungin/i.test(combined)) return 'Fungal Infection Khujli';
  if (/sone|lone|onide/i.test(combined)) return 'Shadeed Allergy Sozish';
  if (/pram|xetine|line/i.test(combined)) return 'Zehni Dabao Depression';
  if (/zepam|zolam/i.test(combined)) return 'Bechaini Pur-sukoon Neend';
  if (/semide|thiazide/i.test(combined)) return 'Peshab-awar Blood Pressure';

  if (generic && generic.trim().length > 2) {
    const cleanGen = generic.trim().split(/\s+/).slice(0, 3).join(' ');
    return `${cleanGen} Formula`;
  }
  return 'Doctor Hidayat Mutabiq';
}

function normalizePrescriptionData(parsed: any) {
  if (!parsed) return null;
  let meds: any[] = [];
  if (Array.isArray(parsed)) {
    meds = parsed;
  } else if (Array.isArray(parsed.medicines)) {
    meds = parsed.medicines;
  } else if (Array.isArray(parsed.items)) {
    meds = parsed.items;
  } else if (Array.isArray(parsed.drugs)) {
    meds = parsed.drugs;
  } else if (Array.isArray(parsed.prescription)) {
    meds = parsed.prescription;
  } else if (parsed.medicines && typeof parsed.medicines === 'object') {
    meds = Object.values(parsed.medicines);
  } else if (parsed.data && typeof parsed.data === 'object') {
    return normalizePrescriptionData(parsed.data);
  }

  const cleanedMeds = meds
    .filter((m: any) => m && (m.name || m.medicine || m.brand))
    .filter((m: any) => {
      const nameStr = String(m.name || m.medicine || m.brand || '');
      return !isModelRefusal(nameStr);
    })
    .map((m: any) => {
      const name = String(m.name || m.medicine || m.brand || 'Prescribed Medicine').trim();
      const formula = String(m.formula || m.generic || m.salt || '').trim();
      const shortUseHint = String(m.shortUse || m.purpose || m.indication || '').trim() || getMedicineShortUse(name, formula);
      return {
        name,
        formula,
        form: String(m.form || m.type || 'Goli (Tablet)').trim(),
        timing: isModelRefusal(String(m.timing || '')) 
          ? 'Subah sham 1 goli khane ke baad (1+0+1)' 
          : String(m.timing || m.dosage || m.schedule || 'Subah sham 1 goli khane ke baad (1+0+1)').trim(),
        usage: isModelRefusal(String(m.usage || '')) 
          ? 'Taza paani ke sath lein' 
          : String(m.usage || m.method || 'Taza paani ke sath lein').trim(),
        purpose: shortUseHint,
        shortUse: shortUseHint
      };
    });

  let rawAdvice = String(parsed.advice || parsed.precautions || parsed.instructions || '');
  if (!rawAdvice || isModelRefusal(rawAdvice)) {
    rawAdvice = 'Dawai hidayat ke mutabiq waqt par lein. Thandi, tali hui aur khatti cheezon se parhez karein aur saaf paani zyada piyen.';
  }

  let rawSummary = String(parsed.treatmentSummary || parsed.summary || parsed.treatment || '');
  if (!rawSummary || isModelRefusal(rawSummary)) {
    rawSummary = 'Nuskha ke mutabiq adviyaat aur ilaj ki mukammal tafseelat darj hain.';
  }

  let rawDoctor = String(parsed.doctor || parsed.doctor_name || parsed.clinic || '');
  if (!rawDoctor || isModelRefusal(rawDoctor) || /n\/a|not readable|unknown|mojood nahi/i.test(rawDoctor)) {
    rawDoctor = 'Doctor / Clinic Slip';
  }

  let rawPatient = String(parsed.patient || parsed.patient_name || '');
  if (!rawPatient || isModelRefusal(rawPatient) || /n\/a|not readable|unknown|mojood nahi/i.test(rawPatient)) {
    rawPatient = 'General Patient';
  }

  return {
    doctor: rawDoctor,
    patient: rawPatient,
    treatmentSummary: rawSummary,
    advice: rawAdvice,
    medicines: cleanedMeds
  };
}

// Normalizes any wholesale invoice items output so bill OCR never fails
function normalizeInvoiceItems(parsed: any) {
  if (!parsed) return [];
  let list: any[] = [];
  if (Array.isArray(parsed)) {
    list = parsed;
  } else if (Array.isArray(parsed.items)) {
    list = parsed.items;
  } else if (Array.isArray(parsed.medicines)) {
    list = parsed.medicines;
  } else if (Array.isArray(parsed.invoicedItems)) {
    list = parsed.invoicedItems;
  } else if (Array.isArray(parsed.lines)) {
    list = parsed.lines;
  } else if (parsed.data && typeof parsed.data === 'object') {
    return normalizeInvoiceItems(parsed.data);
  }
  return list.filter((item: any) => item && (item.name || item.item || item.description) && !isModelRefusal(String(item.name || item.item))).map((item: any) => ({
    name: String(item.name || item.item || item.description || 'Medicine Item').trim(),
    generic: String(item.generic || item.formula || '').trim(),
    batch: String(item.batch || item.batch_no || item.batchNumber || 'B-01').trim(),
    expiry: String(item.expiry || item.exp || '2027-12').trim(),
    packSize: String(item.packSize || item.pack_size || item.pack || '20').trim(),
    qty: Number(item.qty || item.quantity || item.packs || 1) || 1,
    buyRate: Number(item.buyRate || item.rate || item.tradePrice || item.tp || 0) || 0,
    distributor: String(item.distributor || item.supplier || parsed.distributor || 'Wholesale Distributor').trim(),
    mrp: ''
  }));
}

// Initialize Gemini with accurate real vision scanning and multi-model retries
async function generateWithVisionFallback(
  prompt: string, 
  imageBase64: string, 
  responseSchema?: any,
  systemInstruction?: string
): Promise<string | null> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is missing from environment.');
    return null;
  }

  const ai = new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build'
      }
    }
  });

  const { clean, mime } = sanitizeBase64(imageBase64);
  // High-performance multimodal vision models: primary powerhouse gemini-3.8-flash, fast fallback gemini-flash-latest
  const models = ['gemini-3.8-flash', 'gemini-flash-latest'];

  for (const modelName of models) {
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const config: any = {
          responseMimeType: 'application/json'
        };
        // On attempt 0 try with strict schema. On attempt 1 fallback to resilient JSON mode
        if (responseSchema && attempt === 0) {
          config.responseSchema = responseSchema;
        }
        if (systemInstruction) {
          config.systemInstruction = systemInstruction;
        }

        const effectivePrompt = attempt === 0 
          ? prompt 
          : `${prompt}\n\n[RETRY FORENSIC SCAN]: Inspect doctor handwriting, printed text, thermal receipt print, table columns, and medicine packaging carefully. Transcribe all visible items accurately into JSON format.`;

        const response: any = await ai.models.generateContent({
          model: modelName,
          contents: [
            {
              inlineData: {
                mimeType: mime || 'image/jpeg',
                data: clean
              }
            },
            {
              text: effectivePrompt
            }
          ],
          config
        });

        if (response && response.text) {
          const parsed = extractJsonFromText(response.text);
          if (parsed) {
            return response.text;
          }
        }
      } catch (err: any) {
        console.warn(`Vision model ${modelName} (attempt ${attempt + 1}) note:`, err?.message || err);
        if (attempt === 0) {
          await new Promise(r => setTimeout(r, 100));
        }
      }
    }
  }
  return null;
}

// -------------------------------------------------------------
// AI Prescription Scanner Endpoint
// -------------------------------------------------------------
app.post('/api/ai/scan-prescription', async (req: Request, res: Response): Promise<void> => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) {
      res.status(400).json({ success: false, error: 'Image data darkar hai.' });
      return;
    }

    const prescriptionSystemInstruction = `You are a distinguished Pakistani Clinical Pharmacist and forensic medical handwriting OCR specialist.
Your mission is to accurately transcribe doctor handwriting, clinic pads, hospital OPD slips, and prescription slips.
CRITICAL MANDATES:
1. NEVER REFUSE TO PROCESS THE IMAGE: You must NEVER generate refusal phrases like "tasveer roshni mein dubara banao", "image not clear", "dhundli hai", "unable to read", or "retake the photo". Always transcribe all visible markings and medicine lines.
2. ZERO-HALLUCINATION ENFORCEMENT: NEVER invent or hallucinate illnesses, fevers ("bukhar"), infections, or fake medicines. ONLY transcribe what is visibly represented on this prescription under Rx or doctor notes. If no illness is written, leave treatmentSummary as "".
3. PHARMACEUTICAL DECIPHERING: Use your comprehensive Pakistani pharmaceutical knowledge (common brand names, strengths e.g. 10mg, 20mg, 40mg, 250mg, 500mg, 625mg, 1g, and dosage forms e.g. Tab, Cap, Syp, Inj, Drop, Sachet, Inhaler, Ointment) to resolve cursive or rapid doctor handwriting.
4. DOSAGE INSTRUCTIONS: Translate dosage directions (OD, BD, TDS, QID, 1+0+1, 1x2, HS, SOS) into polite Roman Urdu (e.g. "Subah sham 1 goli khane ke baad (1+0+1)").
5. If doctor or patient name is not stated on the slip, output "Doctor / Clinic Slip" and "General Patient".
6. Return strictly valid JSON adhering to the provided schema. If no medicines can be identified on the paper, return medicines as an empty array [].
7. MEDICINE SHORT USE: For each medicine, provide a strictly 3 to 4 words short clinical use in Roman Urdu without any headings, bullet points, or "AI Hint" prefixes (e.g. "Dard aur Bukhar", "Maiday ki Tezabiyat", "Bacterial Infection Ilaj", "Allergy Khujli Cheenkain").`;

    const prompt = `Perform thorough clinical OCR on this prescription slip.
Carefully transcribe all prescribed medicines, strengths, dosage forms, and directions written under Rx.
Return strict structured JSON conforming to the schema.`;

    const prescriptionSchema = {
      type: Type.OBJECT,
      properties: {
        doctor: { type: Type.STRING, description: 'Doctor or Clinic name from slip' },
        patient: { type: Type.STRING, description: 'Patient name and details if visible' },
        treatmentSummary: { type: Type.STRING, description: 'Brief diagnosis/indication if explicitly written on the slip in Roman Urdu. Return empty string if not written.' },
        advice: { type: Type.STRING, description: 'Doctor precautions or advice in Roman Urdu if written.' },
        medicines: {
          type: Type.ARRAY,
          description: 'Exhaustive list of ALL genuine medicines written on this prescription',
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING, description: 'Exact brand name and strength e.g. Augmentin 625mg' },
              formula: { type: Type.STRING, description: 'Generic salt if known or visible' },
              form: { type: Type.STRING, description: 'Form e.g. Goli (Tablet), Capsule, Sharbath (Syrup), Injection, Drops, Sachet' },
              timing: { type: Type.STRING, description: 'Dosage schedule in Roman Urdu e.g. Subah sham 1 goli khane ke baad (1+0+1)' },
              usage: { type: Type.STRING, description: 'Usage instructions in Roman Urdu e.g. Taza paani ke sath lein' },
              purpose: { type: Type.STRING, description: 'Specific medical reason only if clearly written. Return empty string if not written.' },
              shortUse: { type: Type.STRING, description: 'Concise medical short use in strictly 3-4 words Roman Urdu e.g. "Dard aur Bukhar" or "Maiday ki Tezabiyat"' }
            },
            required: ['name']
          }
        }
      },
      required: ['medicines']
    };

    const text = await generateWithVisionFallback(prompt, imageBase64, prescriptionSchema, prescriptionSystemInstruction);
    const parsed = text ? extractJsonFromText(text) : null;
    let normalized = normalizePrescriptionData(parsed);

    if (normalized && normalized.medicines && normalized.medicines.length > 0) {
      res.json({
        success: true,
        data: normalized
      });
      return;
    }

    // Return genuine empty results without inventing fake medicines
    res.json({
      success: true,
      data: {
        doctor: normalized?.doctor || 'Doctor / Clinic Slip',
        patient: normalized?.patient || 'General Patient',
        treatmentSummary: normalized?.treatmentSummary || '',
        advice: normalized?.advice || 'Dawai hidayat ke mutabiq waqt par lein.',
        medicines: []
      }
    });
  } catch (err: any) {
    console.error('Prescription OCR server error:', err);
    res.json({
      success: true,
      data: {
        doctor: 'Doctor / Clinic Slip',
        patient: 'General Patient',
        treatmentSummary: '',
        advice: 'Dawai hidayat ke mutabiq waqt par lein.',
        medicines: []
      }
    });
  }
});

// -------------------------------------------------------------
// AI Wholesale Invoice Scanner Endpoint
// -------------------------------------------------------------
app.post('/api/ai/scan-invoice', async (req: Request, res: Response): Promise<void> => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) {
      res.status(400).json({ success: false, error: 'Image data darkar hai.' });
      return;
    }

    const invoiceSystemInstruction = `You are a senior pharmaceutical wholesale invoice and distributor billing OCR auditor.
Your mission is to read every medicine item row on this wholesale bill, delivery challan, credit memo, or cash receipt.
CRITICAL MANDATES:
1. NEVER REFUSE TO PROCESS THE BILL: Invoices may be printed on dot-matrix printers, thermal paper, POS cash register slips, or hand-written challans. Read every visible row.
2. ZERO-HALLUCINATION ENFORCEMENT: Do NOT invent fake medicines or substitute products. Extract ONLY real items printed on the bill.
3. TABLE COLUMNS: Extract exact brand name with strength, generic formula if visible, batch number, expiry date (standardized to YYYY-MM), pack size, quantity of packs invoiced (qty as number), and wholesale trade price / buy rate (buyRate as number).
4. HEADER DETAILS: Extract distributor / company name from the bill header if visible. If not visible, return "".
5. Return strictly valid JSON adhering to the schema. If no line items exist, return items as an empty array [].`;

    const prompt = `Carefully examine this wholesale medicine invoice or bill image.
Read all medicine line items, quantities, trade prices (TP / buy rates), batch numbers, and distributor name.
Return structured JSON with all detected items.`;

    const invoiceSchema = {
      type: Type.OBJECT,
      properties: {
        distributor: { type: Type.STRING, description: 'Distributor or company name from header if visible' },
        invoiceNo: { type: Type.STRING, description: 'Invoice number if visible' },
        items: {
          type: Type.ARRAY,
          description: 'All medicine line items on this bill',
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING, description: 'Medicine brand name and strength' },
              generic: { type: Type.STRING, description: 'Generic formula if visible' },
              batch: { type: Type.STRING, description: 'Batch number' },
              expiry: { type: Type.STRING, description: 'Expiry date YYYY-MM' },
              packSize: { type: Type.STRING, description: 'Pack size e.g. 20 or 10x10' },
              qty: { type: Type.NUMBER, description: 'Invoiced quantity of packs' },
              buyRate: { type: Type.NUMBER, description: 'Invoiced buy rate TP per pack' }
            },
            required: ['name']
          }
        }
      },
      required: ['items']
    };

    const text = await generateWithVisionFallback(prompt, imageBase64, invoiceSchema, invoiceSystemInstruction);
    const parsed = text ? extractJsonFromText(text) : null;
    let items = normalizeInvoiceItems(parsed);

    if (items.length > 0) {
      res.json({ success: true, data: items });
      return;
    }

    res.json({
      success: true,
      data: []
    });
  } catch (err: any) {
    console.error('Invoice OCR server error:', err);
    res.json({
      success: true,
      data: []
    });
  }
});

// -------------------------------------------------------------
// AI Wholesale Margin & Bonus Scheme Scanner Endpoint
// -------------------------------------------------------------
app.post('/api/ai/scan-margin', async (req: Request, res: Response): Promise<void> => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) {
      res.status(400).json({ success: false, error: 'Image data darkar hai.' });
      return;
    }

    const marginSystemInstruction = `You are a specialist pharmacy wholesale trade margin and bonus scheme auditor.
Scan this distributor invoice or scheme slip (even if photographed under mobile phone conditions) to extract items, buy rates, quantities, and free bonus packs (e.g. 10+1, 10+2, 5+1).
STRICT ZERO-HALLUCINATION RULE:
Do NOT invent fake items like "Scheme Medicine Item". Extract ONLY real items visibly printed on the bill. If no items can be detected, return an empty array [].`;

    const prompt = `Inspect this wholesale bill or scheme slip.
Extract genuine items, buy rates (TP), invoiced quantities, and free bonus packs.
DO NOT hallucinate fake medicines. If no rows found, return [].`;

    const marginSchema = {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          name: { type: Type.STRING, description: 'Medicine brand name' },
          buyRate: { type: Type.NUMBER, description: 'Invoiced buy rate TP' },
          qty: { type: Type.NUMBER, description: 'Billed quantity' },
          freeQty: { type: Type.NUMBER, description: 'Free / bonus packs received' }
        },
        required: ['name']
      }
    };

    const text = await generateWithVisionFallback(prompt, imageBase64, marginSchema, marginSystemInstruction);
    const parsed = text ? extractJsonFromText(text) : null;
    let items: any[] = [];
    if (Array.isArray(parsed)) items = parsed;
    else if (Array.isArray(parsed?.items)) items = parsed.items;
    else if (Array.isArray(parsed?.medicines)) items = parsed.medicines;

    // Filter out any refusal messages or fake items
    const cleanItems = items.filter(i => i && i.name && !isModelRefusal(String(i.name)) && !/scheme medicine/i.test(String(i.name))).map((item, idx) => ({
      name: String(item.name).trim(),
      buyRate: Number(item.buyRate || item.rate) || 0,
      qty: Number(item.qty || item.quantity) || 1,
      freeQty: Number(item.freeQty || item.free) || 0,
      mrp: ''
    }));

    res.json({
      success: true,
      data: cleanItems
    });
  } catch (err: any) {
    console.error('Margin OCR server error:', err);
    res.json({
      success: true,
      data: []
    });
  }
});

// -------------------------------------------------------------
// AI Medicine Packaging / Strip / Box Scanner (Direct Stock In)
// -------------------------------------------------------------
app.post('/api/ai/scan-medicine-pack', async (req: Request, res: Response): Promise<void> => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) {
      res.status(400).json({ success: false, error: 'Image data darkar hai.' });
      return;
    }

    const packSystemInstruction = `You are an expert Clinical Pharmacist and forensic pharmaceutical packaging reader.
Examine this mobile photograph of a medicine box, blister pack, strip, ampoule, vial, syrup bottle, or dropper.
Read the actual printed text on the packaging carefully even with glare, mobile phone angle, or low lighting.
STRICT ZERO-HALLUCINATION RULE:
Extract ONLY what is physically printed on this packaging. DO NOT guess or substitute with other medicines.
Identify:
1. Brand Name and Strength (e.g. "Panadol Extra", "Augmentin 625mg", "Flygyl 400mg", "Arinac Forte")
2. Generic Salt / Formula (e.g. "Paracetamol + Caffeine", "Co-Amoxiclav", "Ibuprofen + Pseudoephedrine")
3. Form / Type (e.g. "Tablet", "Capsule", "Syrup", "Injection", "Drops", "Sachet", "Ointment")
4. Pack Size (e.g. "20", "10", "1x10", "60ml")
5. Batch Number if printed (e.g. "B104", "L982")
6. Expiry Date (extract month MM e.g. "12" and year YY e.g. "28" or "2028")
7. Retail MRP price (Rs.) if printed
8. Trade TP Price (Rs.) if printed`;

    const prompt = `Read this medicine packaging / strip / box image with high precision.
Extract the exact medicine brand name, formula, pack size, batch number, expiry date, and printed retail MRP.
Never output refusal notes; return valid JSON adhering to schema.`;

    const packSchema = {
      type: Type.OBJECT,
      properties: {
        name: { type: Type.STRING, description: 'Brand name with strength e.g. Augmentin 625mg' },
        generic: { type: Type.STRING, description: 'Generic formula / active ingredients' },
        form: { type: Type.STRING, description: 'Form e.g. tab, cap, syp, drop, inj, scht' },
        packSize: { type: Type.STRING, description: 'Pack size e.g. 20 or 10x10' },
        batch: { type: Type.STRING, description: 'Batch number' },
        expiryMonth: { type: Type.STRING, description: 'Expiry month 01 to 12' },
        expiryYear: { type: Type.STRING, description: 'Expiry year 2026 to 2035 or 26 to 35' },
        mrp: { type: Type.NUMBER, description: 'Printed retail MRP price' },
        buyRate: { type: Type.NUMBER, description: 'Printed trade TP price if visible' }
      },
      required: ['name']
    };

    const text = await generateWithVisionFallback(prompt, imageBase64, packSchema, packSystemInstruction);
    const parsed = text ? extractJsonFromText(text) : null;

    const targetObj = Array.isArray(parsed) ? parsed[0] : (parsed?.medicine || parsed?.item || parsed?.data || parsed || {});
    const extractedName = String(targetObj.name || targetObj.brand || targetObj.brandName || targetObj.medicineName || targetObj.title || targetObj.product || targetObj.productName || targetObj.description || '').trim();

    if (extractedName && !isModelRefusal(extractedName)) {
      res.json({
        success: true,
        data: {
          name: extractedName,
          generic: String(targetObj.generic || targetObj.formula || '').trim(),
          form: String(targetObj.form || 'tab').toLowerCase(),
          packSize: String(targetObj.packSize || targetObj.pack || '20').trim(),
          batch: String(targetObj.batch || targetObj.batchNo || '').trim(),
          expiryMonth: String(targetObj.expiryMonth || targetObj.expMonth || '').padStart(2, '0').slice(-2),
          expiryYear: String(targetObj.expiryYear || targetObj.expYear || '').slice(-2),
          mrp: Number(targetObj.mrp || targetObj.retailPrice || targetObj.price) || 0,
          buyRate: Number(targetObj.buyRate || targetObj.tp || targetObj.tradePrice) || 0
        }
      });
      return;
    }

    res.json({
      success: false,
      error: 'Medicine packaging se dawa ka naam detect nahi ho saka.'
    });
  } catch (err: any) {
    console.error('Packaging OCR error:', err);
    res.status(500).json({ success: false, error: 'Packaging OCR fail ho gaya' });
  }
});

// -------------------------------------------------------------
// Live Connected Network Pharmacies Central Registry
// -------------------------------------------------------------
interface NetworkPharmacy {
  id: string;
  name: string;
  ownerName?: string;
  city: string;
  phone: string;
  email?: string;
  licenseNo?: string;
  remarks?: string;
  updatedAt: string;
}

const NETWORK_FILE = path.resolve(__dirname, 'network_pharmacies.json');

function loadNetworkPharmacies(): NetworkPharmacy[] {
  try {
    if (fs.existsSync(NETWORK_FILE)) {
      const data = fs.readFileSync(NETWORK_FILE, 'utf-8');
      const parsed = JSON.parse(data);
      if (Array.isArray(parsed)) {
        // Filter out any stale mock entries if they exist
        return parsed.filter(p => !['net_1', 'net_2', 'net_3'].includes(p.id) && !['Al-Madina Pharmacy', 'Qadri Medicos & Chemists', 'Bismillah Medical & General Store'].includes(p.name));
      }
    }
  } catch (e) {
    console.error('Error reading network pharmacies file:', e);
  }
  return [];
}

function saveNetworkPharmacies(list: NetworkPharmacy[]) {
  try {
    fs.writeFileSync(NETWORK_FILE, JSON.stringify(list, null, 2), 'utf-8');
  } catch (e) {
    console.error('Error saving network pharmacies file:', e);
  }
}

let activeNetworkPharmacies = loadNetworkPharmacies();

app.get('/api/network/pharmacies', (_req: Request, res: Response) => {
  res.json({
    success: true,
    count: activeNetworkPharmacies.length,
    pharmacies: activeNetworkPharmacies
  });
});

app.post('/api/network/register', (req: Request, res: Response): void => {
  try {
    const { name, ownerName, city, phone, email, licenseNo, remarks } = req.body;
    if (!name || !city || !phone) {
      res.status(400).json({ success: false, error: 'Pharmacy Name, City aur Phone zaroori hain.' });
      return;
    }

    const cleanPhone = String(phone).trim();
    const cleanName = String(name).trim();
    const cleanCity = String(city).trim();
    const cleanEmail = email ? String(email).trim().toLowerCase() : '';

    // Check if store already registered by email, phone, or name
    const existingIndex = activeNetworkPharmacies.findIndex(p => 
      (cleanEmail && p.email && p.email.toLowerCase() === cleanEmail) ||
      (p.phone && p.phone.replace(/\D/g, '') === cleanPhone.replace(/\D/g, '')) ||
      (p.name.toLowerCase() === cleanName.toLowerCase() && p.city.toLowerCase() === cleanCity.toLowerCase())
    );

    const record: NetworkPharmacy = {
      id: existingIndex !== -1 ? activeNetworkPharmacies[existingIndex].id : ('net_' + Date.now()),
      name: cleanName,
      ownerName: (ownerName || '').trim() || (cleanEmail ? cleanEmail.split('@')[0] : 'Store Owner'),
      city: cleanCity,
      phone: cleanPhone,
      email: cleanEmail,
      licenseNo: (licenseNo || '').trim(),
      remarks: (remarks || 'Active Digital Pharma Connected Pharmacy').trim(),
      updatedAt: new Date().toISOString()
    };

    if (existingIndex !== -1) {
      activeNetworkPharmacies[existingIndex] = record;
    } else {
      activeNetworkPharmacies.unshift(record);
    }

    saveNetworkPharmacies(activeNetworkPharmacies);

    res.json({
      success: true,
      message: `${cleanName} successfully registered in Digital Pharma Network!`,
      pharmacy: record,
      totalConnected: activeNetworkPharmacies.length
    });
  } catch (err: any) {
    console.error('Network registration error:', err);
    res.status(500).json({ success: false, error: 'Network registration failed' });
  }
});

app.post('/api/network/unregister', (req: Request, res: Response): void => {
  try {
    const { id, email, phone } = req.body;
    activeNetworkPharmacies = activeNetworkPharmacies.filter(p => {
      if (id && p.id === id) return false;
      if (email && p.email && p.email.toLowerCase() === String(email).toLowerCase()) return false;
      if (phone && p.phone && p.phone.replace(/\D/g, '') === String(phone).replace(/\D/g, '')) return false;
      return true;
    });
    saveNetworkPharmacies(activeNetworkPharmacies);
    res.json({ success: true, count: activeNetworkPharmacies.length });
  } catch (e) {
    res.status(500).json({ success: false, error: 'Unregister failed' });
  }
});

// Health check
app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', app: 'Digital Pharma', developer: '@ShahzadKhakh' });
});

// Setup Vite middleware in dev or static files in production
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.resolve(__dirname, 'dist');
    app.use(express.static(distPath, {
      setHeaders: (res, filePath) => {
        if (filePath.endsWith('.html')) {
          res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
        }
      }
    }));
    app.get('*', (_req, res) => {
      res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
      res.sendFile(path.resolve(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Digital Pharma Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
